# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"\x17\n\x07\x41irport\x12\x0c\n\x04name\x18\x02 \x01(\t\"X\n\nFlightInfo\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x1d\n\x0b\x64\x65p_airport\x18\r \x01(\x0b\x32\x08.Airport\x12\x1d\n\x0b\x61rr_airport\x18\x0e \x01(\x0b\x32\x08.Airport\"&\n\x06\x46light\x12\x1c\n\x07\x66lights\x18\x03 \x03(\x0b\x32\x0b.FlightInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AIRPORT']._serialized_start=14
  _globals['_AIRPORT']._serialized_end=37
  _globals['_FLIGHTINFO']._serialized_start=39
  _globals['_FLIGHTINFO']._serialized_end=127
  _globals['_FLIGHT']._serialized_start=129
  _globals['_FLIGHT']._serialized_end=167
# @@protoc_insertion_point(module_scope)
